import { VerticalBox, HorizontalBox, ComboBox, StandardButton, TextEdit } from "std-widgets.slint";
import { Button } from "button.slint";
import { OverwriteDialog } from "overwrite-dialog.slint";
import { ErrorDialog } from "error-dialog.slint";

export { OverwriteDialog, ErrorDialog }

export component AppWindow inherits Window {
    in property <[string]> conda_envs: [];
    in-out property <string> output_folder: "";
    out property <string> output_file_name: "";
    in property <bool> picking: false;

    out property <string> selected_env <=> env_box.current-value;

    callback pick_folder();
    callback create_env_file();

    title: "conda-share";
    min-width: 500px;
    
    VerticalBox {
        alignment: start;

        Text {
            text: "conda-share";
            font-size: 25px;
            horizontal-alignment: center;
        }

        Rectangle {
            border-color: #b0b0b0;
            border-width: 1px;
            background: transparent;
            
            HorizontalBox {
                env_box := ComboBox {
                    enabled: !picking;
                    current-value: "Select conda environment";
                    model: conda_envs;
                    selected(val) => { output_file_name = val + ".yml"; }
                }
            }
        }

        Rectangle {
            border-color: #b0b0b0;
            border-width: 1px;
            background: transparent;
            
            HorizontalBox {
                output_name_text := Text {
                    text: "Output File Name:";
                    vertical-alignment: center;
                }
                TextEdit {
                    enabled: !picking;
                    text <=> output_file_name;
                    height: output_name_text.preferred-height + 9px * 2;
                    font-size: output_name_text.font-size;
                }
            }
        }

        Rectangle {
            border-color: #b0b0b0;
            border-width: 1px;
            background: transparent;
            
            HorizontalBox {
                Button {
                    enabled: !picking;
                    text: "Select output folder";
                    clicked => { pick_folder(); }
                    width: 150px;
                }
                Rectangle {
                    // background: grey;
                    height: selected_folder_text.preferred-height + 6px * 2;
            
                    selected_folder_text := Text {
                        text: output_folder == "" ? "No folder chosen." : output_folder;
                        x: 6px;

                        wrap: word-wrap;
                        vertical-alignment: center;
                        horizontal-alignment: left;

                        width: parent.width - parent.padding * 2;
                    }
                }
            }
        }
        
        HorizontalBox { 
            alignment: center; 
            
            Button {
                text: "Create Env File";
                enabled: selected_env != "" && output_file_name != "" && output_folder != "";
                clicked => { create_env_file(); }
                width: 300px;
                height: 40px;
                font-size: 18px;
            }
        }
    }
}
