export component Button inherits Rectangle {
    // This was created so that we could disable the buttons and change the background color

    in property<bool> enabled: true;
    in property<string> text <=> txt.text;
    in property<length> font-size <=> txt.font-size;

    out property<bool> has-focus <=> fs.has-focus;

    callback clicked <=> touch.clicked;

    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.brighter(20%);
    background: !enabled ? #aaa : touch.pressed ? #6b8282 : touch.has-hover ? #6c616c : #707070;
    min-width: txt.preferred-width + 20px;
    min-height: txt.preferred-height + 10px;
    forward-focus: fs;


    fs := FocusScope {
        enabled: root.enabled;
        key-pressed(event) => {
            if (event.text == Key.Return) {
                root.clicked();
                accept
            }
            reject
        }

        txt := Text {
            x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
            y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
            color: !enabled ? #888 : touch.pressed ? #fff : #eee;
        }

        touch := TouchArea {
            enabled: root.enabled;
        }
    }

    
}