import { StandardButton, Button } from "std-widgets.slint";
export component ErrorDialog inherits Dialog {
    in property<string> error_msg: "";
    
    always-on-top: true;
    title: "Error";
    height: txt.preferred-height + 20px + btn.preferred-height + 20px;
    width: max(300px, txt.preferred-width + 40px);
    forward-focus: btn;

    txt := Text { text <=> error_msg; }
    btn := StandardButton { kind: close; }
}