import { StandardButton, Button } from "std-widgets.slint";
export component NotificationDialog inherits Dialog {
    in property<string> msg: "";
    
    always-on-top: true;
    title: "Notification";
    height: txt.preferred-height + 20px + btn.preferred-height + 20px;
    width: max(300px, txt.preferred-width + 40px);
    forward-focus: btn;

    txt := Text { text <=> msg; max-height: 200px; wrap: word-wrap; }
    btn := StandardButton { kind: close; }
}