import { StandardButton, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
export component OverwriteDialog inherits Dialog {
    in-out property<string> file_path: "";
    in-out property<string> env_name: "";
    in property<string> file_name: "";

    always-on-top: true;
    title: "Overwrite File?";
    height: txt.preferred-height + 20px + btn_ok.preferred-height + 20px;
    width: max(300px, txt.preferred-width + 40px);
    forward-focus: btn_ok;

    txt := Text {
        text: "The file \"" + file_name + "\" already exists. Do you want to overwrite it?";
        height: self.preferred-height;
        wrap: word-wrap;
    }
    btn_ok := StandardButton { kind: ok; }
    btn_cancel := StandardButton { kind: cancel; }
}